
GET http://localhost:3400/alunos
Content-Type: application/json

###

POST http://localhost:3400/alunos
Content-Type: application/json

{
    "ra": "23002302",
    "nome": "João da SIlva",
    "senha": "123456",
    "ano": 1,
    "idCurso": 1
}

###

POST http://localhost:3400/alunos/login
Content-Type: application/json

{
    "ra": "23002302",
    "senha": "123456"
}

###
GET http://localhost:3400/alunos/tokenTests
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhbHVubyI6eyJyYSI6IjIzMDAyMzAyIiwibm9tZSI6Ikpvw6NvIERhIFNpbHZhIiwidGVsZWZvbmUiOm51bGwsImFubyI6MSwiZW1haWwiOiIyMzAwMjMwMkB1ZXBnLmJyIiwic2VuaGEiOiIiLCJhdGl2byI6dHJ1ZSwiY3Vyc28iOnsiaWQiOjEsIm5vbWUiOiJFbmdlbmhhcmlhIGRlIFNvZnR3YXJlIn19LCJpYXQiOjE3NDYwMzg5NDcsImV4cCI6MTc0NjA0NjE0N30.8UBz80OJAUDIgj2WApD20hJO6vwjOhoEYJJHogNbOfU
