
GET http://localhost:3400/curso
Content-Type: application/json

###

POST http://localhost:3400/curso
Content-Type: application/json

{
    "nome": "Engenharia de Software"
}

###

GET http://localhost:3400/curso/1
Content-Type: application/json

###

PUT http://localhost:3400/curso/1
Content-Type: application/json

{
    "nome": "Engenharia de Software Avançada"
}

###

DELETE http://localhost:3400/curso/1
Content-Type: application/json

###

GET http://localhost:3400/curso/?nome=Engenharia
Content-Type: application/json