GET http://localhost:3400/evento/

###

GET http://localhost:3400/evento/1

###

POST http://localhost:3400/evento/
Content-Type: application/json

{
  "nome": "Evento Teste",
  "dataEvento": "2025-07-20",
  "duracao": 120,
  "responsavel": "João Silva",
  "idLaboratorio": 1
}
###

