GET http://localhost:3400/laboratorio/

###

GET http://localhost:3400/laboratorio/1

###

POST http://localhost:3400/laboratorio/
Content-Type: application/json

{
  "numero": "1011",
  "nome": "Laborató1rio de Informática",
  "restrito": false,
  "gerarHorarios": true
}

###

PUT http://localhost:3400/laboratorio/1
Content-Type: application/json

{
  "nome": "l"
}

###


DELETE http://localhost:3400/laboratorio/1