GET http://localhost:3400/permissao/

###

GET http://localhost:3400/permissao/1

###

POST http://localhost:3400/permissao/
Content-Type: application/json

{
  "nomePermissao": "adm",
  "cadastro": "true",
  "relatorio": "true",
  "advertencia": "false"
}

### 

PUT http://localhost:3400/permissao/1
Content-Type: application/json

{
  "nomePermissao": "admin1"
}