GET http://127.0.0.1:3400/tipoUsuario/

###

GET http://localhost:3400/tipoUsuario/1

###

POST http://localhost:3400/tipoUsuario/
Content-Type: application/json

{
  "nome": "Comum",
  "cadastro": "true",
  "alteracao": "false",
  "relatorio": "true",
  "advertencia": "false"
}